#:kivy 1.11.1

<HelpScreen>:
    BoxLayout:
        name: "HelpScreen"
        orientation: "vertical"
        font_name: 'Roboto-Bold.ttf'

<HelpPanels>:
    name: "HelpPanels"
    do_default_tab: False
    size_hint_y: .9
    tab_width: root.width / 3
    
    TabbedPanelStrip:
        background_color: (0, 0, 1, .5)    # 50% translucent blue
        border: [0, 0, 0, 0]
        background_image: ''
    